name: "Bug Report"
description: "File a bug report"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    attributes:
      label: "Is there an existing bug report for this issue?"
      description: "Please search [here](../issues) to see if an issue already exists for the bug you are reporting"
      options:
      - label: "I have searched the existing issues"
        required: true

  - type: textarea
    validations:
      required: true
    attributes:
      label: "What happened?"
      description: "A clear and concise description of what the problem is. Also tell us, what did you expect to happen?"
      placeholder: |
        I have an issue when ...

  - type: textarea
    validations:
      required: true
    attributes:
      label: "Describe the solution you'd like"
      description: "A clear and concise description of what you want to happen. Add any considered drawbacks"

  - type: textarea
    validations:
      required: false
    attributes:
      label: "Teachability, documentation, adoption, migration strategy"
      description: "If you can, explain how we could improve our documentation relating this issue?"

  - type: input
    validations:
      required: true
    attributes:
      label: "Package version?"
      description: "The package version you are using"
