name: "Feature Request"
description: "Suggest an idea for this project"
labels: ["enhancement"]
body:
  - type: textarea
    validations:
      required: true
    attributes:
      label: "Is your feature request related to a problem? Please describe it"
      description: "A clear and concise description of what the problem is"
      placeholder: |
        I have an issue when ...

  - type: textarea
    validations:
      required: true
    attributes:
      label: "Describe the solution you'd like"
      description: "A clear and concise description of what you want to happen. Add any considered drawbacks"

  - type: textarea
    validations:
      required: true
    attributes:
      label: "Teachability, documentation, adoption, migration strategy"
      description: "If you can, explain how users will be able to use this and possibly write out a version the docs. Maybe a screenshot or design?"

  - type: textarea
    validations:
      required: true
    attributes:
      label: "What is the motivation / use case for changing the behavior?"
      description: "Describe the motivation or the concrete use case"
